apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes01
  labels:
    app: kubernetes01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes01
  template:
    metadata:
      labels:
        app: kubernetes01
    spec:
      containers:
        - name: springboot-k8s-example
          image: razdeepak/springboot-k8s-example:1.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: mydocker-hubb
